{% set name = "amazon-braket-sdk" %}
{% set version = "1.29.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-sdk-{{ version }}.tar.gz
  sha256: adc6f269a466af467c018cc86f639002ae57fe192eda41da84c18ac8320fb7ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.2
  run:
    - amazon-braket-schemas >=1.10.1
    - amazon-braket-default-simulator >=1.7.2
    - backoff
    - boltons
    - boto3
    - nest-asyncio
    - networkx
    - numpy
    - python >=3.7.2
    - sympy

test:
  imports:
    - braket
    - braket._sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-sdk-python
  summary: An open source library for interacting with quantum computing devices on Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://amazon-braket-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
